import { NextRequest, NextResponse } from 'next/server';

import { isDashboardSlug } from '@/lib/dashboard-slug';

/**
 * GET /dashboard/[slug]/sw.js
 *
 * A deliberately minimal service worker, served from inside the slug directory.
 *
 * ── The scope is the security property, not just a detail ────────────────────
 *
 * A service worker's scope is the directory it is served from (unless widened by
 * a `Service-Worker-Allowed` header, which this route deliberately does NOT send).
 * Serving it from `/dashboard/<slug>/` therefore means it can only ever intercept
 * requests under that path: it cannot touch the marketing site, and it cannot
 * touch `/api/dashboard/<slug>`, which lives outside the scope. That containment
 * is why this is a scoped route rather than a file dropped in `public/`.
 *
 * The existing `public/sw.js` is the cautionary example — it caches every request
 * cache-first and, at `/sw.js`, would have scope over the whole site, so a single
 * registration would serve stale HTML to visitors indefinitely. Nothing registers
 * it today, which is the only reason it is harmless.
 *
 * ── Offline is best-effort here, and this file does not claim otherwise ──────
 *
 * The shell and the icons are precached so the app opens instantly and does not
 * show a browser error offline. The dashboard's own JavaScript chunks live under
 * `/_next/`, outside this scope, so the SW cannot precache them — offline they
 * come from the browser's HTTP cache or not at all. That is an accepted limit:
 * the requirement is "opens full-screen like an app", not "works offline", and
 * the numbers are worthless stale anyway. A half-working offline mode that shows
 * last week's figures as if they were current would be worse than an honest error.
 *
 * ── No API response is ever cached ──────────────────────────────────────────
 *
 * The fetch handler refuses anything that is not a same-origin GET, and refuses
 * `/api/` outright. This is belt-and-braces given the scope already excludes the
 * API, and it matters because a cached lead count is a stale lead count.
 */

export const dynamic = 'force-dynamic';

export async function GET(
  _request: NextRequest,
  { params }: { params: { slug: string } },
) {
  if (!isDashboardSlug(params.slug)) {
    return new NextResponse('Not found', {
      status: 404,
      headers: { 'Cache-Control': 'no-store' },
    });
  }

  const base = `/dashboard/${params.slug}`;

  const script = `/* Service worker for the private Upgrade Roofs dashboard.
 *
 * Generated by app/dashboard/[slug]/sw.js/route.ts — edit that, not this.
 * Scope: ${base}/  (a directory, so it cannot affect the rest of the site)
 */
const CACHE = 'ur-dashboard-v1';
/* The shell and the icons. Both are inside this worker's scope. */
const SHELL = ['${base}', '/dashboard/icon-192.png', '/dashboard/icon-512.png'];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) =>
      /* addAll rejects the whole install if any single URL 404s, which would
         leave the worker permanently uninstalled with no obvious cause. Each
         entry is added independently so one missing icon cannot do that. */
      Promise.all(SHELL.map((url) => cache.add(url).catch(() => undefined)))
    ).then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (event) => {
  const request = event.request;

  /* Only same-origin GETs, and never the API. A cached lead count is a wrong
     lead count, and this worker has no business holding one. */
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;
  if (url.pathname.startsWith('/api/')) return;

  /* Navigations: network first, so the figures are always fresh when there is a
     connection, falling back to the cached shell only when there is not. */
  if (request.mode === 'navigate') {
    event.respondWith(
      fetch(request)
        .then((response) => {
          const copy = response.clone();
          caches.open(CACHE).then((cache) => cache.put('${base}', copy)).catch(() => undefined);
          return response;
        })
        .catch(() => caches.match('${base}').then((hit) => hit || Response.error()))
    );
    return;
  }

  /* Everything else in scope: cache first, then network. These are the icons —
     static by definition, so a cached copy is always correct. */
  event.respondWith(
    caches.match(request).then((hit) => hit || fetch(request))
  );
});
`;

  return new NextResponse(script, {
    status: 200,
    headers: {
      'Content-Type': 'application/javascript; charset=utf-8',
      // Revalidate rather than cache long: a stale worker is a stale app, and
      // browsers cap SW script caching at 24h regardless.
      'Cache-Control': 'no-cache, must-revalidate',
      'X-Robots-Tag': 'noindex, nofollow',
      // Explicitly NOT sending Service-Worker-Allowed: the default (this
      // directory, and nothing above it) is the containment we want.
    },
  });
}
